### PR TITLE
fix(CSS): fix for TypeScript 3.9+

### PR DESCRIPTION
**Pull request by waterplea**
## PR Checklist

Please check if your PR fulfills the following requirements:

-   [ ] The commit message follows [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)
-   [ ] Tests for the changes have been added (for bug fixes / features)
-   [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

-   [ ] Bugfix
-   [ ] Feature
-   [ ] Refactoring (no functional changes, no api changes)
-   [ ] Other... Please describe:

## What is the current behavior?

Issue Number: N/A

## Does this PR introduce a breaking change?

-   [ ] Yes
-   [ ] No

### CODE REVIEW

**Comment by IllusionMH** [comment]
You can use `typeof CSS` to get type with both static methods from CSS namespace. [Example](https://www.typescriptlang.org/play/index.html#code/CYUwxgNghgTiAEYD2A7AzgF0QV00gtgMIDKxAXPBgJ4AOISAZvCcQNwCwAUF8ulhgEYKmGAEsUAc3gBeHHiKkAdCDRgodABQByRQyRIAxACNYWgJQdOvTJQBMFI-oggoKGXIwEWitNho0kGAw0DQAiDBAADwwAWlBkGCgMUVQYzCpnUIAaeFCjCHEAa1CLHlQbDABmBycXN1kwXE8FYh8-AKCQ0OBRNBpoKgoGZ0iSrnHOIA)

**Comment by waterplea** [comment]
I knew I can do typeof CSS but CSS is also the name of token so it didn't work, although I haven't thought of creating utility type in a separate file. Seems like a better way to handle it, thanks for bringing it up!

**Comment by waterplea** [comment]
Tried it and it didn't work, unfortunately naming convention for Angular token makes token name the same CSS as global CSS so we cannot do `typeof` :(

**Comment by IllusionMH** [comment]
Right, my bad that I've missed local CSS name. And `typeof window.CSS` will only work after 3.6 😞 

I'm sorry for unnecessary ping.

**Pull request merged**
